---
- name: check_reboot | Check if reboot is pending
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: check_reboot | Reboot
  when: reboot_required.stat.exists
  ansible.builtin.reboot:
    msg: Rebooting
    reboot_timeout: 300 # (= 5 minutes)
    post_reboot_delay: 60
